import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createTestClientProtocol} from './fixtures/client-protocol.ts';
import {participantId,participantPublicKey,signParticipantRegistration,verifyParticipantRegistration} from '../packages/protocol/src/registration.ts';
import {isValidOwner,type Owner,type PublicRecipient} from '../packages/protocol/src/types.ts';
import {createPublicCoordinator} from '../src/noncustodial/coordinator.ts';
import {createNoncustodialApp} from '../src/noncustodial/server.ts';
import {createSdkRuntime} from '../src/sdk/runtime.ts';
import {EngineStore} from '../src/storage.ts';

test('public coordinator supports signed arbitrary participants and append-only recovery, transfer and withdrawal',{timeout:240000},async()=>{
 const directory=await mkdtemp(join(tmpdir(),'shielded-participants-'));
 const identities=['61','62','63'].map((byte,index)=>({secret:byte.repeat(32),spend:String(101+index*6),view:String(103+index*6)}));
 const ids=identities.map(value=>participantId(participantPublicKey(value.secret)));
 const clients=await Promise.all(identities.slice(0,2).map((value,index)=>createTestClientProtocol({owner:ids[index]!,keys:{spend:value.spend,view:value.view},entropyLabel:`participant-${index}`})));
 const charlieClient=await createTestClientProtocol({owner:ids[2]!,keys:{spend:identities[2]!.spend,view:identities[2]!.view,},entropyLabel:'participant-2'});
 const proofProfile=clients[0]!.publicCheckpoint().profile;
 const descriptors:Record<Owner,PublicRecipient>={};clients.forEach((client,index)=>{descriptors[ids[index]!]=client.publicDescriptor();});descriptors[ids[2]!]=charlieClient.publicDescriptor();
 const participants=identities.map((value,index)=>signParticipantRegistration({network:'local-emulator',profile:proofProfile,secretKey:value.secret,recipient:descriptors[ids[index]!]!}));
 let coordinator=await createPublicCoordinator(directory);const receipts:any[]=[];
 const listener=createNoncustodialApp(coordinator).listen(0,'127.0.0.1');await new Promise<void>(resolve=>listener.once('listening',resolve));
 const address=listener.address() as {port:number};const base=`http://127.0.0.1:${address.port}`;
 const registerHttp=async(value:typeof participants[number],body=value)=>{const response=await fetch(`${base}/api/participants/${value.owner}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({recipient:body.recipient,nativePublicKey:body.nativePublicKey,authorization:body.authorization})});return {status:response.status,body:await response.json()};};
 try{
  assert.equal(coordinator.profile().phase,'registration');assert.equal(coordinator.profile().ready,false);assert.equal(coordinator.profile().profile,proofProfile);assert.equal(coordinator.profile().registration.profile,proofProfile);
  const badProfile={...participants[0]!,authorization:{...participants[0]!.authorization,profile:'f'.repeat(64)}};
  const rejectedProfile=await registerHttp(participants[0]!,badProfile);assert.equal(rejectedProfile.status,400);
  const registerA=await registerHttp(participants[0]!);assert.equal(registerA.status,200);assert.equal(registerA.body.phase,'registration');
  assert.equal(coordinator.profile().ready,false);
  await assert.rejects(coordinator.register('bob',{recipient:descriptors[ids[1]!]!,nativePublicKey:participants[0]!.nativePublicKey}),/Native participant key is already registered/);
  const registerB=await registerHttp(participants[1]!);assert.equal(registerB.status,200);assert.equal(registerB.body.ready,true);
  const firstArchive=coordinator.archive().archive;clients[0]!.setRecipients(firstArchive.recipients);clients[1]!.setRecipients(firstArchive.recipients);clients[0]!.restorePublicCheckpoint(firstArchive);
  const profile=coordinator.profile();const probe=await createSdkRuntime({verificationKeys:profile.verificationKeys as Record<string,unknown>,initialState:firstArchive.state,registry:{file:join(directory,'probe-registry.json'),recipientPublicKeys:Object.fromEntries(Object.entries(profile.participants).map(([owner,value])=>[owner,value!.nativePublicKey]))}});
  assert.throws(()=>probe.destination('constructor'),/outside this native registry/);assert.throws(()=>probe.destination('toString'),/outside this native registry/);await probe.close();
  const shield=await clients[0]!.prepareShield(ids[0]!,'BTC',1000);receipts.push(await coordinator.submit(shield));receipts.push(await coordinator.seal());
  const beforeAppend=coordinator.archive().archive;
  const charlie=participants[2]!;
  assert.equal(verifyParticipantRegistration({...charlie,recipient:{...charlie.recipient,owner:'8'}},'local-emulator',proofProfile),false);
  await assert.rejects(coordinator.register(charlie.owner,{recipient:{...charlie.recipient,owner:'8'},nativePublicKey:charlie.nativePublicKey,authorization:charlie.authorization}),/signature is invalid/);
  const dana=signParticipantRegistration({network:'local-emulator',profile:proofProfile,secretKey:'64'.repeat(32),recipient:descriptors[ids[0]!]!});
  await assert.rejects(coordinator.register(dana.owner,{recipient:dana.recipient,nativePublicKey:dana.nativePublicKey,authorization:dana.authorization}),/Duplicate public recipient key/);
  const wrongNetwork=signParticipantRegistration({network:'mutinynet',profile:proofProfile,secretKey:'65'.repeat(32),recipient:descriptors[ids[2]!]!});
  await assert.rejects(coordinator.register(wrongNetwork.owner,{recipient:wrongNetwork.recipient,nativePublicKey:wrongNetwork.nativePublicKey,authorization:wrongNetwork.authorization}),/signature is invalid/);
  await assert.rejects(coordinator.register('__proto__' as Owner,{recipient:charlie.recipient,nativePublicKey:charlie.nativePublicKey,authorization:charlie.authorization}),/Invalid public participant identity/);
  const registryBefore=await readFile(join(directory,'registry.json'));const originalSave=EngineStore.prototype.save;EngineStore.prototype.save=function(value:any){if(Object.hasOwn(value.participants??{},charlie.owner))throw new Error('Injected append persistence failure');return originalSave.call(this,value);};
  try{const interrupted=await registerHttp(charlie);assert.equal(interrupted.status,400);}finally{EngineStore.prototype.save=originalSave;}
  assert.equal(coordinator.profile().participants[charlie.owner],undefined);assert.deepEqual(coordinator.archive().archive,beforeAppend);assert.deepEqual(await readFile(join(directory,'registry.json')),registryBefore);
  const registerCharlie=await registerHttp(charlie);assert.equal(registerCharlie.status,200);assert.equal(registerCharlie.body.ready,true);
  assert.equal(coordinator.profile().ready,true);assert.deepEqual(coordinator.archive().archive.state,beforeAppend.state);
  const archive=coordinator.archive().archive,all=archive.recipients;
  clients[0]!.setRecipients(all);clients[1]!.setRecipients(all);
  charlieClient.setRecipients(all);
  clients[0]!.restorePublicCheckpoint(archive);clients[1]!.restorePublicCheckpoint(archive);charlieClient.restorePublicCheckpoint(archive);
  const transfer=await clients[0]!.prepareTransfer(ids[0]!,ids[2]!,'BTC',400);receipts.push(await coordinator.submit(transfer));receipts.push(await coordinator.seal());
  const afterTransfer=coordinator.archive().archive;clients[0]!.restorePublicCheckpoint(afterTransfer);clients[1]!.restorePublicCheckpoint(afterTransfer);charlieClient.restorePublicCheckpoint(afterTransfer);
  assert.equal(charlieClient.snapshot().wallets[ids[2]!]!.balances.BTC,400);
  const destination=coordinator.profile().destinations?.[ids[2]!];assert.ok(destination);
  const withdrawal=await charlieClient.prepareWithdraw(ids[2]!,'BTC',150,destination!);receipts.push(await coordinator.submit(withdrawal));receipts.push(await coordinator.seal());
  const finalArchive=coordinator.archive().archive;charlieClient.restorePublicCheckpoint(finalArchive);
  assert.equal(charlieClient.snapshot().wallets[ids[2]!]!.balances.BTC,250);
  assert.equal('wallets' in finalArchive,false);assert.deepEqual(Object.keys(finalArchive.recipients).sort(),ids.slice().sort());
  assert.ok(receipts.every(value=>value.receipt));
  assert.equal(isValidOwner('__proto__'),false);assert.equal(isValidOwner('constructor'),false);
  const duplicate={...all,[ids[2]!]:descriptors[ids[0]!]};
  await assert.rejects(createTestClientProtocol({owner:ids[2]!,keys:{spend:identities[2]!.spend,view:identities[2]!.view},recipients:duplicate,entropyLabel:'participant-duplicate'}),/Duplicate public recipient key|Client keys do not match/);
  await coordinator.close();coordinator=await createPublicCoordinator(directory);
  assert.deepEqual(coordinator.archive().archive,finalArchive);assert.equal(coordinator.profile().ready,true);assert.equal(coordinator.profile().participants[ids[2]!]?.nativePublicKey,ids[2]);
  const replay=await coordinator.submit(withdrawal);assert.equal(replay.replay,true);assert.deepEqual(coordinator.archive().archive,finalArchive);
 }finally{await new Promise<void>((resolve,reject)=>listener.close(error=>error?reject(error):resolve()));await coordinator.close();await rm(directory,{recursive:true,force:true});}
});

after(async()=>{await (globalThis as any).curve_bn128?.terminate();});
