package main

import (
	"encoding/hex"
	"encoding/json"
	"math/big"
	"os"
	"testing"

	"github.com/btcsuite/btcd/wire/v2"
)

// Generated by tools/rollup-covenant-fixture.mjs from the toy circuits in
// circuits/rollup/covenant-*.circom.
const rollupSnarkJSFixturePath = "testdata/rollup-covenant-snarkjs.json"

type rollupSnarkJSProof struct {
	Proof struct {
		A []string   `json:"pi_a"`
		B [][]string `json:"pi_b"`
		C []string   `json:"pi_c"`
	} `json:"proof"`
	PublicSignals []string `json:"publicSignals"`
}

type rollupSnarkJSFixture struct {
	ClientKey     snarkJSVerificationKey `json:"clientKey"`
	BatchKey      snarkJSVerificationKey `json:"batchKey"`
	OldPacket     string                      `json:"oldPacket"`
	NewPacket     string                      `json:"newPacket"`
	PayoutProgram string                      `json:"payoutProgram"`
	Slots         []rollupSnarkJSProof        `json:"slots"`
	Batch         rollupSnarkJSProof          `json:"batch"`
}

func rollupFixtureWitness(t *testing.T, f rollupSnarkJSFixture) wire.TxWitness {
	t.Helper()
	proofItems := func(p rollupSnarkJSProof) [][]byte {
		items, err := rollupProofItems(p.Proof.A, p.Proof.B, p.Proof.C)
		if err != nil {
			t.Fatal(err)
		}
		return items
	}
	witness := wire.TxWitness(proofItems(f.Batch))
	for i := len(f.Slots) - 1; i >= 0; i-- {
		var x []*big.Int
		for _, text := range f.Slots[i].PublicSignals {
			v, ok := new(big.Int).SetString(text, 10)
			if !ok {
				t.Fatalf("slot %d has a malformed public signal %q", i, text)
			}
			x = append(x, v)
		}
		witness = append(witness, proofItems(f.Slots[i])...)
		witness = append(witness, rollupPublicItems(x)...)
	}
	return witness
}

func TestRollupBatchLeafVerifiesSnarkJSProofs(t *testing.T) {
	raw, err := os.ReadFile(rollupSnarkJSFixturePath)
	if err != nil {
		t.Fatal(err)
	}
	var f rollupSnarkJSFixture
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatal(err)
	}
	client, err := parseRollupKey(f.ClientKey, 5)
	if err != nil {
		t.Fatal(err)
	}
	batch, err := parseRollupKey(f.BatchKey, 12)
	if err != nil {
		t.Fatal(err)
	}
	decode := func(text string) []byte {
		b, err := hex.DecodeString(text)
		if err != nil {
			t.Fatal(err)
		}
		return b
	}
	w := newRollupWorld(t, 11, 0, 1)
	if w.leaf, err = buildRollupBatchLeaf(rollupLeafConfig{Slots: 11, Client: client, Batch: batch}); err != nil {
		t.Fatal(err)
	}
	newPacket := decode(f.NewPacket)
	w.oldPacket, w.newState, w.newDA = decode(f.OldPacket), newPacket[:32], newPacket[32:]
	legs := make([]rollupLeg, 11)
	legs[1] = rollupLeg{dep: 2500, inSats: 2500}
	legs[3] = rollupLeg{wd: 1000, dest: decode(f.PayoutProgram)}
	b := w.batchOf(legs, false)
	b.witness = rollupFixtureWitness(t, f)
	if err := b.execute(); err != nil {
		t.Fatalf("real snarkjs batch rejected: %v", err)
	}
	f.Slots[0].PublicSignals[0] = "5"
	b.witness = rollupFixtureWitness(t, f)
	rollupExpectReject(t, "a pub the proofs did not sign", b, "OP_VERIFY")
}
