import React,{useRef,useState,useEffect} from 'react';
import './client-wallet.css';
import {schnorr} from '@noble/curves/secp256k1.js';
import {bytesToHex,hexToBytes} from '@noble/hashes/utils.js';
import {createBrowserClient} from '../../packages/protocol/src/browser.ts';
import type {ClientProtocolKernel,Owner,WalletKeys,PreparedSettlement,Asset} from '../../packages/protocol/src/types.ts';
import {encryptWallet,decryptWallet,type EncryptedWallet} from './wallet-backup.ts';
interface Backup {version:1;owner:Owner;keys:WalletKeys;nativeSecret:string;profile:string;pending?:PreparedSettlement;lastArchive?:ReturnType<ClientProtocolKernel['publicCheckpoint']>}
export default function NoncustodialWallet(){
 const [owner,setOwner]=useState<Owner>('alice'),[password,setPassword]=useState(''),[token,setToken]=useState(''),[profile,setProfile]=useState<any>(),[wallet,setWallet]=useState<any>(),[asset,setAsset]=useState<Asset>('BTC'),[amount,setAmount]=useState('10000'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[unlocked,setUnlocked]=useState(false);
 const client=useRef<ClientProtocolKernel|undefined>(undefined),backup=useRef<Backup|undefined>(undefined),imported=useRef<EncryptedWallet|undefined>(undefined);const storageKey='shielded-client-v1-'+owner;
 const api=async(path:string,body?:unknown)=>{const response=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await response.json();if(!response.ok)throw new Error(data.error??'Request rejected');return data;};
 const persist=async()=>{if(!backup.current)throw new Error('Wallet is locked');localStorage.setItem(storageKey,JSON.stringify(await encryptWallet(backup.current,password)));};
 const refresh=async()=>{let next=await api('profile');setProfile(next);if(!client.current)return;if(!next.participants?.[owner]&&next.phase==='registration'){next=await api('participants/'+owner,{recipient:client.current.publicDescriptor(),nativePublicKey:bytesToHex(schnorr.getPublicKey(hexToBytes(backup.current!.nativeSecret)))});setProfile(next);}const own=next.participants?.[owner];if(own){if(JSON.stringify(own.recipient)!==JSON.stringify(client.current.publicDescriptor())||own.nativePublicKey!==bytesToHex(schnorr.getPublicKey(hexToBytes(backup.current!.nativeSecret))))throw new Error('Registered participant does not match this wallet');}if(next.phase==='ready'){const recipients={alice:next.participants.alice.recipient,bob:next.participants.bob.recipient};const savedRecipients=backup.current!.lastArchive?.recipients;if(savedRecipients&&JSON.stringify(savedRecipients)!==JSON.stringify(recipients))throw new Error('Registered recipient directory changed');client.current.setRecipients(recipients);const response=await api('archive');const archive=response.archive;if(archive.profile!==backup.current!.profile)throw new Error('Verifier profile changed; refusing to restore');const prior=backup.current!.lastArchive;if(prior&&(archive.state.revision<prior.state.revision||Object.entries(prior.committed).some(([id,fp])=>archive.committed[id]!==fp)))throw new Error('Archive rollback or conflicting history');client.current.restorePublicCheckpoint(archive);backup.current!.lastArchive=archive;const pending=backup.current!.pending;if(pending&&archive.committed[pending.id])delete backup.current!.pending;await persist();}setWallet(client.current.snapshot().wallets[owner]);};
 const run=async(action:()=>Promise<void>)=>{if(busy)return;setBusy(true);setMessage('');try{await action();}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{void api('profile').then(setProfile).catch(error=>setMessage(error.message));},[]);
 const create=()=>run(async()=>{if(localStorage.getItem(storageKey))throw new Error('A saved wallet exists. Unlock or restore it');const value=await createBrowserClient({owner,token});const nativeSecret=crypto.getRandomValues(new Uint8Array(32));const nativePublicKey=bytesToHex(schnorr.getPublicKey(nativeSecret));client.current=value;backup.current={version:1,owner,keys:value.exportWalletKeys(),nativeSecret:bytesToHex(nativeSecret),profile:value.publicCheckpoint().profile};await persist();await api('participants/'+owner,{recipient:value.publicDescriptor(),nativePublicKey});setUnlocked(true);await refresh();setMessage('Wallet created locally. Download its encrypted backup before using it.');});
 const unlock=(encrypted?:EncryptedWallet)=>run(async()=>{const saved=encrypted??imported.current??JSON.parse(localStorage.getItem(storageKey)??'null');const value=await decryptWallet<Backup>(saved,password);if(value.version!==1||value.owner!==owner)throw new Error('Backup belongs to a different participant');const restored=await createBrowserClient({owner,keys:value.keys,token});if(restored.publicCheckpoint().profile!==value.profile)throw new Error('Backup proof profile mismatch');client.current=restored;backup.current=value;setUnlocked(true);await refresh();await persist();setMessage('Wallet restored from your keys and the public archive.');});
 const send=async(prepared:PreparedSettlement)=>{backup.current!.pending=prepared;await persist();await api('settlements',prepared);delete backup.current!.pending;await refresh();await persist();setMessage('Settlement accepted by the independent VM.');};
 const action=(kind:'shield'|'transfer'|'withdraw')=>run(async()=>{if(!client.current||!profile?.ready)throw new Error('Unlock a wallet and register both participants');if(backup.current?.pending)throw new Error('Resolve the pending request first');await refresh();const n=Number(amount);const prepared=kind==='shield'?await client.current.prepareShield(owner,asset,n):kind==='transfer'?await client.current.prepareTransfer(owner,owner==='alice'?'bob':'alice',asset,n):await client.current.prepareWithdraw(owner,asset,n,profile.destinations[owner]);await send(prepared);});
 const download=()=>run(async()=>{await persist();const blob=new Blob([localStorage.getItem(storageKey)!],{type:'application/json'});const href=URL.createObjectURL(blob),link=document.createElement('a');link.href=href;link.download='shielded-'+owner+'-encrypted-backup.json';link.click();URL.revokeObjectURL(href);});
 const lock=()=>{client.current=undefined;backup.current=undefined;imported.current=undefined;setWallet(undefined);setUnlocked(false);setPassword('');};
 return <main className="client-wallet"><h1>Shielded wallet</h1><p>Local test network · synthetic funds · development proof setup</p><p>Your browser holds your spending, viewing, and withdrawal keys. The coordinator receives proofs and encrypted notes.</p>
 <label>Participant <select value={owner} disabled={unlocked||busy} onChange={event=>setOwner(event.target.value as Owner)}><option value="alice">Alice</option><option value="bob">Bob</option></select></label>{' '}
 <label>Wallet passphrase <input aria-label="Wallet passphrase" disabled={busy||unlocked} type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete="off"/></label>{' '}
 <label>Service token (if configured) <input type="password" disabled={busy} value={token} onChange={event=>setToken(event.target.value)}/></label>
 <div style={{display:'flex',gap:12,margin:'20px 0',flexWrap:'wrap'}}><button disabled={busy||unlocked} onClick={create}>Create local wallet</button><button disabled={busy||unlocked} onClick={()=>unlock()}>Unlock saved wallet</button><button disabled={busy||!unlocked} onClick={download}>Download encrypted backup</button><button disabled={busy||!unlocked} onClick={lock}>Lock</button><label>Import encrypted backup <input type="file" accept="application/json" disabled={busy||unlocked} onChange={event=>{const file=event.target.files?.[0];if(file)void run(async()=>{const encrypted=JSON.parse(await file.text());const value=await decryptWallet<Backup>(encrypted,password);if(value.owner!==owner)throw new Error('Select the backup participant first');imported.current=encrypted;setMessage('Backup imported. Unlock it to verify and restore.');});}}/></label></div>
 <p>{profile?.phase==='registration'?'Register Alice and Bob in separate browser profiles, or lock one participant and create the other. The public recipient registry freezes once both join.':profile?.blockedReason||'The coordinator is ready.'}</p>
 {unlocked&&<><h2>{owner} balances</h2><p>BTC: {wallet?.balances?.BTC??0} sats · pending {wallet?.pending?.BTC??0} | DEMO: {wallet?.balances?.DEMO??0} · pending {wallet?.pending?.DEMO??0}</p><select aria-label="Asset" value={asset} disabled={busy} onChange={event=>setAsset(event.target.value as Asset)}><option>BTC</option><option>DEMO</option></select>{' '}<input aria-label="Amount" type="number" min="1" value={amount} disabled={busy} onChange={event=>setAmount(event.target.value)}/><div style={{display:'flex',gap:12,margin:'20px 0',flexWrap:'wrap'}}><button disabled={busy||!profile?.ready} onClick={()=>action('shield')}>Deposit test funds</button><button disabled={busy||!profile?.ready} onClick={()=>run(async()=>{await api('seal',{});await refresh();setMessage('Notes sealed; no participant had to be online.');})}>Seal pending notes</button><button disabled={busy||!profile?.ready} onClick={()=>action('transfer')}>Pay {owner==='alice'?'Bob':'Alice'}</button><button disabled={busy||!profile?.ready} onClick={()=>action('withdraw')}>Withdraw to my Ark key</button><button disabled={busy} onClick={()=>run(refresh)}>Refresh archive</button>{backup.current?.pending&&<button disabled={busy} onClick={()=>run(async()=>{await refresh();if(backup.current?.pending)await send(backup.current.pending);else setMessage('The pending request was already accepted.');})}>Resolve same pending request</button>}</div><details><summary>My decrypted notes</summary><pre>{JSON.stringify(wallet?.notes?.map((note:any)=>({amount:note.amount,asset:note.asset,spent:note.spent,spendable:note.spendable})),null,2)}</pre></details></>}
 <p role="status" aria-live="polite">{busy?'Working locally; proof generation may take a moment.':message}</p><p>This prototype needs the registered verifier deployed on the Ark emulator for live use. It currently has a bounded note tree and no independent pooled-BTC exit.</p></main>;
}
