import React,{useRef,useState,useEffect} from 'react';
import './client-wallet.css';
import {bytesToHex} from '@noble/hashes/utils.js';
import {createBrowserClient} from '../../packages/protocol/src/browser.ts';
import {deriveWalletKeyMaterial,parseMasterSecret} from '../../packages/protocol/src/wallet-keys.ts';
import {participantId,participantPublicKey,signParticipantRegistration,verifyParticipantRegistration,type RegistrationNetwork,type RegistrationPayload} from '../../packages/protocol/src/registration.ts';
import {isValidOwner,LEGACY_OWNERS,type ClientProtocolKernel,type Owner,type PublicRecipient,type WalletKeys,type PreparedSettlement,type Asset} from '../../packages/protocol/src/types.ts';
import {encryptWallet,decryptWallet,type EncryptedWallet} from './wallet-backup.ts';
interface LegacyBackup {version:1;owner:Owner;keys:WalletKeys;nativeSecret:string;profile:string;pending?:PreparedSettlement;lastArchive?:ReturnType<ClientProtocolKernel['publicCheckpoint']>}
interface AliasBackup {version:2;owner:Owner;keyDerivation:{version:1;network:string};masterSecret:string;profile:string;pending?:PreparedSettlement;lastArchive?:ReturnType<ClientProtocolKernel['publicCheckpoint']>}
interface ParticipantRecord {recipient:PublicRecipient;nativePublicKey:string;authorization?:RegistrationPayload['authorization']}
interface Backup {version:3;owner:Owner;keyDerivation:{version:1;network:RegistrationNetwork};masterSecret:string;profile:string;pendingRegistration?:RegistrationPayload;lastDirectory?:Record<Owner,ParticipantRecord>;pending?:PreparedSettlement;lastArchive?:ReturnType<ClientProtocolKernel['publicCheckpoint']>}
type WalletBackup=LegacyBackup|AliasBackup|Backup;
const ACTIVE_WALLET_KEY='shielded-client-active-v2';
const walletStorageKey=(value:WalletBackup)=>value.version===3?'shielded-client-v3-'+value.owner:'shielded-client-v1-'+value.owner;
function registrationNetwork(profile:any):RegistrationNetwork {
 const network=profile?.registration?.network;
 if((network!=='local-emulator'&&network!=='mutinynet')||profile.network!==network)throw new Error('The operator network is missing or inconsistent');
 return network;
}
function directoryOf(profile:any,previous?:Record<Owner,ParticipantRecord>):Record<Owner,ParticipantRecord> {
 const network=registrationNetwork(profile),participants=profile?.participants;
 if(!/^[0-9a-f]{64}$/.test(profile?.profile))throw new Error('The operator proof profile is unavailable');
 if(!participants||typeof participants!=='object'||Array.isArray(participants))throw new Error('The operator participant directory is unavailable');
 const directory=participants as Record<Owner,ParticipantRecord>;
 for(const [owner,value] of Object.entries(directory)){
  if(!isValidOwner(owner)||!value?.recipient||!/^[0-9a-f]{64}$/.test(value.nativePublicKey))throw new Error('The operator participant directory is invalid');
  if(value.authorization){if(!verifyParticipantRegistration({owner,recipient:value.recipient,nativePublicKey:value.nativePublicKey,authorization:value.authorization},network,profile.profile))throw new Error('A participant registration signature is invalid');}
  else if(network!=='local-emulator'||!LEGACY_OWNERS.includes(owner as typeof LEGACY_OWNERS[number]))throw new Error('An unsigned participant is not allowed on this network');
 }
 if(previous)for(const [owner,value] of Object.entries(previous))if(!directory[owner]||JSON.stringify(directory[owner])!==JSON.stringify(value))throw new Error('A previously registered wallet changed its identity');
 return directory;
}
function recipientMap(directory:Record<Owner,ParticipantRecord>):Record<Owner,PublicRecipient>{return Object.fromEntries(Object.entries(directory).map(([owner,value])=>[owner,value.recipient]));}
function sameRegistration(value:ParticipantRecord|undefined,payload:RegistrationPayload){return !!value&&value.nativePublicKey===payload.nativePublicKey&&JSON.stringify(value.recipient)===JSON.stringify(payload.recipient)&&JSON.stringify(value.authorization)===JSON.stringify(payload.authorization);}
export default function NoncustodialWallet(){
 const [owner,setOwner]=useState<Owner>('alice'),[recipientId,setRecipientId]=useState(''),[password,setPassword]=useState(''),[recoverySecret,setRecoverySecret]=useState(''),[showRecoverySecret,setShowRecoverySecret]=useState(false),[token,setToken]=useState(''),[profile,setProfile]=useState<any>(),[wallet,setWallet]=useState<any>(),[asset,setAsset]=useState<Asset>('BTC'),[amount,setAmount]=useState('10000'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[unlocked,setUnlocked]=useState(false);
 const client=useRef<ClientProtocolKernel|undefined>(undefined),backup=useRef<WalletBackup|undefined>(undefined),material=useRef<{keys:WalletKeys;nativeSecret:string}|undefined>(undefined),imported=useRef<EncryptedWallet|undefined>(undefined);
 const api=async(path:string,body?:unknown)=>{const response=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await response.json();if(!response.ok)throw new Error(data.error??'Request rejected');return data;};
 const persist=async()=>{if(!backup.current)throw new Error('Wallet is locked');const key=walletStorageKey(backup.current);localStorage.setItem(key,JSON.stringify(await encryptWallet(backup.current,password)));localStorage.setItem(ACTIVE_WALLET_KEY,key);};
 const refresh=async()=>{const next=await api('profile');setProfile(next);if(!client.current||!backup.current||!material.current)return next;const walletOwner=backup.current.owner,network=registrationNetwork(next),directory=directoryOf(next,backup.current.version===3?backup.current.lastDirectory:undefined),own=directory[walletOwner];if(backup.current.version!==1&&network!==backup.current.keyDerivation.network)throw new Error('Wallet network changed; refusing to derive or restore keys');if(!own||own.nativePublicKey!==participantPublicKey(material.current.nativeSecret)||JSON.stringify(own.recipient)!==JSON.stringify(client.current.publicDescriptor()))throw new Error('This wallet is not present in the signed operator directory');if(backup.current.version===3&&backup.current.pendingRegistration&&!sameRegistration(own,backup.current.pendingRegistration))throw new Error('Wallet registration is still pending; finish registration before restoring');if(backup.current.version===3&&backup.current.lastArchive)for(const [id,recipient] of Object.entries(backup.current.lastArchive.recipients))if(!directory[id]||JSON.stringify(directory[id].recipient)!==JSON.stringify(recipient))throw new Error('A previously known recipient changed');client.current.setRecipients(recipientMap(directory));if(next.ready){if(next.profile!==backup.current.profile)throw new Error('Verifier profile changed; refusing to restore');const archive=(await api('archive')).archive;if(archive.profile!==backup.current.profile)throw new Error('Archive verifier profile changed; refusing to restore');const prior=backup.current.lastArchive;if(prior&&(archive.state.revision<prior.state.revision||Object.entries(prior.committed).some(([id,fp])=>archive.committed[id]!==fp)))throw new Error('Archive rollback or conflicting history');client.current.restorePublicCheckpoint(archive);backup.current.lastArchive=archive;const pending=backup.current.pending;if(pending&&archive.committed[pending.id])delete backup.current.pending;}else if(backup.current.lastArchive?.state.revision)throw new Error('The operator archive is unavailable for this wallet history');if(backup.current.version===3){backup.current.lastDirectory=structuredClone(directory);delete backup.current.pendingRegistration;}await persist();setWallet(client.current.snapshot().wallets[walletOwner]);return next;};
  const run=async(action:()=>Promise<void>)=>{if(busy)return;setBusy(true);setMessage('');try{await action();}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}};
  useEffect(()=>{void api('profile').then(setProfile).catch(error=>setMessage(error.message));},[]);
  const registerPending=async()=>{const saved=backup.current;if(!saved||saved.version!==3||!saved.pendingRegistration)throw new Error('No wallet registration is pending');const pending=saved.pendingRegistration,before=await api('profile'),network=registrationNetwork(before);if(network!==pending.authorization.network)throw new Error('The registered network changed');if(before.profile!==pending.authorization.profile||before.profile!==saved.profile)throw new Error('The registered verifier profile changed');let after=before,directory=directoryOf(before,saved.lastDirectory);const existing=directory[pending.owner];if(existing){if(!sameRegistration(existing,pending))throw new Error('This wallet ID is already registered to different keys');}else after=await api('participants/'+pending.owner,{recipient:pending.recipient,nativePublicKey:pending.nativePublicKey,authorization:pending.authorization});directory=directoryOf(after,saved.lastDirectory);if(!sameRegistration(directory[pending.owner],pending))throw new Error('The operator did not preserve the signed wallet registration');if(after.profile!==saved.profile)throw new Error('The registered verifier profile differs from this wallet');saved.lastDirectory=structuredClone(directory);delete saved.pendingRegistration;await persist();setProfile(after);await refresh();setOwner(saved.owner);setUnlocked(true);setMessage(after.ready?'Wallet registered and public archive verified.':'Wallet registered. It will be available when another user joins the pool.');};
  const create=()=>run(async()=>{if(password.length<12)throw new Error('Use a wallet passphrase of at least 12 characters');if(localStorage.getItem(ACTIVE_WALLET_KEY)||localStorage.getItem('shielded-client-v1-'+owner))throw new Error('A saved wallet exists. Unlock it or use a separate browser profile');const configured=await api('profile'),network=registrationNetwork(configured),secret=crypto.getRandomValues(new Uint8Array(32)),masterSecret=bytesToHex(secret),derived=deriveWalletKeyMaterial(secret,network),nativePublicKey=participantPublicKey(derived.nativeSecret),walletOwner=participantId(nativePublicKey),value=await createBrowserClient({owner:walletOwner,keys:derived.keys,token}),proofProfile=value.publicCheckpoint().profile,payload=signParticipantRegistration({network,profile:proofProfile,secretKey:derived.nativeSecret,recipient:value.publicDescriptor()});client.current=value;material.current=derived;backup.current={version:3,owner:walletOwner,keyDerivation:{version:1,network},masterSecret,profile:proofProfile,pendingRegistration:payload,lastDirectory:structuredClone(directoryOf(configured))};setOwner(walletOwner);setProfile(configured);await persist();await registerPending();setRecoverySecret(masterSecret);setShowRecoverySecret(false);setMessage('Wallet created. Save its recovery secret and encrypted backup. The secret never leaves this browser.');});
  const unlock=(encrypted?:EncryptedWallet)=>run(async()=>{const activeKey=localStorage.getItem(ACTIVE_WALLET_KEY),storageKey=activeKey??'shielded-client-v1-'+owner,raw=encrypted??imported.current??JSON.parse(localStorage.getItem(storageKey)??'null'),value=await decryptWallet<WalletBackup>(raw,password);let keys:WalletKeys,nativeSecret:string;if(value.version===1){keys=value.keys;nativeSecret=value.nativeSecret;}else if((value.version===2||value.version===3)&&value.keyDerivation.version===1){const derived=deriveWalletKeyMaterial(value.masterSecret,value.keyDerivation.network);keys=derived.keys;nativeSecret=derived.nativeSecret;}else throw new Error('Unsupported wallet backup version');const restored=await createBrowserClient({owner:value.owner,keys,token});if(restored.publicCheckpoint().profile!==value.profile)throw new Error('Backup proof profile mismatch');client.current=restored;material.current={keys,nativeSecret};backup.current=value;setOwner(value.owner);if(value.version===3&&value.pendingRegistration){setProfile(await api('profile'));setMessage('Wallet setup is incomplete. Verify the saved identity, then finish registration.');return;}try{await refresh();setUnlocked(true);await persist();setMessage(value.version===1?'Legacy wallet restored. Keep this encrypted backup; its original keys are preserved.':value.version===2?'Legacy wallet restored. Keep this encrypted backup; its original owner ID is preserved.':'Wallet restored from your encrypted recovery secret and the public archive.');}catch(error){client.current=undefined;material.current=undefined;backup.current=undefined;throw error;}});
  const recover=()=>run(async()=>{if(password.length<12)throw new Error('Use a wallet passphrase of at least 12 characters');if(localStorage.getItem(ACTIVE_WALLET_KEY))throw new Error('A saved wallet exists; unlock it first so pending operations are preserved');const master=parseMasterSecret(recoverySecret),registered=await api('profile'),network=registrationNetwork(registered),directory=directoryOf(registered),derived=deriveWalletKeyMaterial(master,network),nativePublicKey=participantPublicKey(derived.nativeSecret),probe=await createBrowserClient({owner:participantId(nativePublicKey),keys:derived.keys,token}),descriptor=probe.publicDescriptor(),canonical=directory[nativePublicKey];let walletOwner=nativePublicKey;if(canonical){if(canonical.nativePublicKey!==nativePublicKey||JSON.stringify(canonical.recipient)!==JSON.stringify(descriptor))throw new Error('Recovery secret does not match the registered wallet');}else{const matches=Object.entries(directory).filter(([id,value])=>LEGACY_OWNERS.includes(id as typeof LEGACY_OWNERS[number])&&value.nativePublicKey===nativePublicKey&&JSON.stringify(value.recipient)===JSON.stringify(descriptor));if(matches.length!==1)throw new Error('Recovery secret does not match one unique registered wallet');walletOwner=matches[0][0];}if(!registered.ready||!registered.profile)throw new Error('The operator archive is not ready for recovery');if(probe.publicCheckpoint().profile!==registered.profile)throw new Error('Recovery verifier profile mismatch');if(localStorage.getItem('shielded-client-v3-'+walletOwner)||localStorage.getItem('shielded-client-v1-'+walletOwner))throw new Error('A saved wallet exists; unlock it first so pending operations are preserved');const value=walletOwner===nativePublicKey?probe:await createBrowserClient({owner:walletOwner,keys:derived.keys,token});client.current=value;material.current=derived;backup.current={version:3,owner:walletOwner,keyDerivation:{version:1,network},masterSecret:bytesToHex(master),profile:value.publicCheckpoint().profile,lastDirectory:structuredClone(directory)};try{await refresh();setOwner(walletOwner);setUnlocked(true);setRecoverySecret('');setShowRecoverySecret(false);setMessage('Wallet and notes restored from the operator archive. Archive freshness is not independently checked against Arkade; reconcile any interrupted transaction before retrying.');}catch(error){client.current=undefined;material.current=undefined;backup.current=undefined;throw error;}});
 const send=async(prepared:PreparedSettlement)=>{backup.current!.pending=prepared;await persist();await api('settlements',prepared);delete backup.current!.pending;await refresh();await persist();setMessage('Settlement accepted by the independent VM.');};
  const action=(kind:'shield'|'transfer'|'withdraw')=>run(async()=>{if(!client.current||!backup.current)throw new Error('Unlock a registered wallet');if(backup.current.pending)throw new Error('Resolve the pending request first');const current=await refresh(),walletOwner=backup.current.owner;if(!current?.ready)throw new Error(current?.blockedReason||'The pool is waiting for its users');const n=Number(amount);let prepared:PreparedSettlement;if(kind==='shield')prepared=await client.current.prepareShield(walletOwner,asset,n);else if(kind==='transfer'){const directory=directoryOf(current);if(!recipientId||recipientId===walletOwner||!directory[recipientId])throw new Error('Choose a recipient from the signed wallet directory');prepared=await client.current.prepareTransfer(walletOwner,recipientId,asset,n);}else{const destination=current.destinations?.[walletOwner];if(!destination)throw new Error('This wallet has no registered Ark withdrawal address');prepared=await client.current.prepareWithdraw(walletOwner,asset,n,destination);}await send(prepared);});
  const download=()=>run(async()=>{if(!backup.current)throw new Error('Unlock a wallet first');await persist();const blob=new Blob([localStorage.getItem(walletStorageKey(backup.current))!],{type:'application/json'});const href=URL.createObjectURL(blob),link=document.createElement('a');link.href=href;link.download='shielded-'+backup.current.owner+'-encrypted-backup.json';link.click();URL.revokeObjectURL(href);});
  const lock=()=>{client.current=undefined;backup.current=undefined;material.current=undefined;imported.current=undefined;setWallet(undefined);setUnlocked(false);setPassword('');setRecoverySecret('');setShowRecoverySecret(false);};
  const recoverableBackup=backup.current?.version===2||backup.current?.version===3?backup.current:undefined;
  const participants=profile?.participants as Record<Owner,ParticipantRecord>|undefined;
  return <main className="client-wallet"><h1>Shielded wallet</h1><p>Local test network · synthetic funds · development proof setup</p><p>Your browser holds your spending, viewing, and withdrawal keys. The coordinator receives proofs and encrypted notes.</p>
  {!unlocked&&<details><summary>Legacy wallet</summary><label>Legacy wallet ID <select value={owner} disabled={busy} onChange={event=>setOwner(event.target.value as Owner)}><option value="alice">Alice</option><option value="bob">Bob</option></select></label></details>}
 <label>Wallet passphrase <input aria-label="Wallet passphrase" disabled={busy||unlocked} type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete="off"/></label>{' '}
 <label>Master recovery secret <input aria-label="Master recovery secret" disabled={busy||unlocked} type="password" value={recoverySecret} onChange={event=>setRecoverySecret(event.target.value.trim())} autoComplete="off"/></label>{' '}
 <label>Service token (if configured) <input type="password" disabled={busy} value={token} onChange={event=>setToken(event.target.value)}/></label>
  <div style={{display:'flex',gap:12,margin:'20px 0',flexWrap:'wrap'}}><button disabled={busy||unlocked} onClick={create}>Create wallet</button><button disabled={busy||unlocked} onClick={()=>unlock()}>Unlock saved wallet</button><button disabled={busy||unlocked||!recoverySecret||password.length<12} onClick={recover}>Recover notes with secret</button><button disabled={busy||!unlocked} onClick={download}>Download encrypted backup</button><button disabled={busy||!unlocked} onClick={lock}>Lock</button><label>Import encrypted backup <input type="file" accept="application/json" disabled={busy||unlocked} onChange={event=>{const file=event.target.files?.[0];if(file)void run(async()=>{const encrypted=JSON.parse(await file.text());const value=await decryptWallet<WalletBackup>(encrypted,password);imported.current=encrypted;setOwner(value.owner);setMessage('Encrypted backup loaded. Unlock it to verify and restore.');});}}/></label>{backup.current?.version===3&&backup.current.pendingRegistration&&<button disabled={busy} onClick={()=>run(registerPending)}>Finish wallet setup</button>}</div>
 {recoverableBackup&&<details><summary>Recovery secret (keep private)</summary><p>This secret recreates your spending, viewing and Ark withdrawal keys for {recoverableBackup.keyDerivation.network}. Anyone who gets it can control this wallet.</p><button disabled={busy} onClick={()=>setShowRecoverySecret(value=>!value)}>{showRecoverySecret?'Hide recovery secret':'Reveal recovery secret'}</button>{showRecoverySecret&&<><pre aria-label="Recovery secret">{recoverableBackup.masterSecret}</pre><button disabled={busy} onClick={()=>void navigator.clipboard.writeText(recoverableBackup.masterSecret)}>Copy recovery secret</button></>}</details>}
  <p>{profile?.blockedReason||(!profile?.ready?`Waiting for ${profile?.registration?.minimumParticipants??2} registered wallets before the synthetic pool can run.`:'The pool is ready for synthetic test actions.')}</p>
  {unlocked&&<><h2>Your wallet</h2><p>Wallet ID: <code>{backup.current?.owner}</code> <button disabled={busy} onClick={()=>void navigator.clipboard.writeText(backup.current?.owner??'')}>Copy ID</button></p><p>BTC: {wallet?.balances?.BTC??0} sats · pending {wallet?.pending?.BTC??0} | DEMO: {wallet?.balances?.DEMO??0} · pending {wallet?.pending?.DEMO??0}</p><select aria-label="Asset" value={asset} disabled={busy} onChange={event=>setAsset(event.target.value as Asset)}><option>BTC</option><option>DEMO</option></select>{' '}<input aria-label="Amount" type="number" min="1" value={amount} disabled={busy} onChange={event=>setAmount(event.target.value)}/><label>Send to wallet ID<input list="shielded-wallet-directory" value={recipientId} disabled={busy} onChange={event=>setRecipientId(event.target.value)} placeholder="Paste a recipient ID"/></label><datalist id="shielded-wallet-directory">{Object.keys(participants??{}).filter(id=>id!==backup.current?.owner).map(id=><option key={id} value={id}/>)}</datalist><div style={{display:'flex',gap:12,margin:'20px 0',flexWrap:'wrap'}}><button disabled={busy||!profile?.ready} onClick={()=>action('shield')}>Deposit synthetic test funds</button><button disabled={busy||!profile?.ready} onClick={()=>run(async()=>{await api('seal',{});await refresh();setMessage('Notes sealed; no participant had to be online.');})}>Seal pending notes</button><button disabled={busy||!profile?.ready||!recipientId} onClick={()=>action('transfer')}>Send to selected wallet</button><button disabled={busy||!profile?.ready} onClick={()=>action('withdraw')}>Withdraw to my Ark address</button><button disabled={busy} onClick={()=>run(refresh)}>Refresh archive</button>{backup.current?.pending&&<button disabled={busy} onClick={()=>run(async()=>{await refresh();if(backup.current?.pending)await send(backup.current.pending);else setMessage('The pending request was already accepted.');})}>Resolve same pending request</button>}</div><details><summary>My decrypted notes</summary><pre>{JSON.stringify(wallet?.notes?.map((note:any)=>({amount:note.amount,asset:note.asset,spent:note.spent,spendable:note.spendable})),null,2)}</pre></details></>}
  <p role="status" aria-live="polite">{busy?'Working locally; proof generation may take a moment.':message}</p><p>Deposits in this lab are synthetic. The UI is not connected to customer deposits or live Mutinynet transactions. Note capacity is bounded, and holders do not yet have an independent pooled-BTC exit.</p></main>;
}
