import {useStockSetup,stockSetupPresentation} from './stock-setup.ts';
import App from './App';
import './shielded-home.css';

const steps=[
 {name:'Deposit',text:'Fund your Ark wallet, then move BTC into the shared pool. The deposit creates a pending note for your wallet. This movement into the pool is public.',flow:'Your Ark BTC → pending note'},
 {name:'Seal',text:'A proof checks the pending state and commits the notes to the pool. Your wallet stores the information needed to recognize and spend your notes.',flow:'Pending note → spendable shielded note'},
 {name:'Transfer',text:'Your browser proves that you own the input notes and that their value is conserved. It consumes those notes and creates new notes for the recipient and any change.',flow:'Your notes → recipient notes + change'},
 {name:'Withdraw',text:'Your browser proves a valid note spend and binds the payout destination. BTC leaves the pool for the selected Ark destination. This movement out of the pool is public.',flow:'Your notes → Ark BTC'}
];

export default function ShieldedHome(){
 const {setup,supported,error}=useStockSetup();
 const phase=setup?.phase;
 const presentation=stockSetupPresentation(setup,error);
 const title=error?'Could not read service status':presentation.title;
 if(supported===false)return <App/>;
 return <div className="shielded-home">
  <header className="sh-header"><a className="sh-brand" href="/" aria-label="Shielded home">SHIELDED <span>ARKADE · MUTINYNET</span></a><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#recovery">Recovery</a><a className="sh-button" href="/stock-wallet">Open wallet <span aria-hidden="true">↗</span></a></nav></header>
  <main className="sh-main">
   <section className="sh-intro" aria-labelledby="sh-title"><div><p className="sh-label">BTC PRIVACY EXPERIMENT / MUTINYNET</p><h1 id="sh-title">Your keys.<br/>Shielded notes.<br/>Bitcoin on Arkade.</h1><p className="sh-lead">Move test BTC into a shared pool, transfer private notes, and withdraw back to Ark. Your browser holds the keys and builds the proofs.</p><div className="sh-intro-actions"><a className="sh-button" href="/stock-wallet">Open the wallet <span aria-hidden="true">→</span></a><a href="#how-it-works">Read the flow ↓</a></div><p className="sh-test-note">Mutinynet test BTC only. Development proof setup; this is an experimental deployment.</p></div>
    <aside className="sh-status" aria-label="Live deployment status"><p className="sh-label">THIS DEPLOYMENT</p><div role="status" aria-live="polite"><span className={'sh-status-indicator '+(phase==='ready'&&!error?'is-ready':error||phase==='blocked'?'is-blocked':'')}/><h2>{title}</h2></div><p>{presentation.detail}</p>{presentation.progress&&<p>{presentation.progress.stage}{Number.isSafeInteger(presentation.progress.completed)&&Number.isSafeInteger(presentation.progress.total)?`: ${presentation.progress.completed} of ${presentation.progress.total} checks complete`:""}</p>}{phase==='waiting-funds'&&!error&&<p>The pool has not been created yet. Bootstrap funding is an operator setup step; there is no customer deposit available yet.</p>}<a href="/stock-wallet">View setup in the wallet →</a><small>Status is reported by the service. Your wallet also checks the pinned release and archive before use.</small></aside>
   </section>
   <section id="how-it-works" className="sh-section" aria-labelledby="sh-flow-title"><div className="sh-section-heading"><p className="sh-label">01 / THE MONEY FLOW</p><h2 id="sh-flow-title">From public BTC to notes, and back.</h2><p>A note is a private record of value and ownership. Spending a note reveals a nullifier, a unique marker that prevents it from being spent twice.</p></div><ol className="sh-flow">{steps.map((step,index)=><li key={step.name}><span className="sh-step-number">0{index+1}</span><h3>{step.name}</h3><p>{step.text}</p><span className="sh-flow-label">{step.flow}</span></li>)}</ol></section>
   <section className="sh-section" aria-labelledby="sh-proof-title"><div className="sh-section-heading"><p className="sh-label">02 / WHO DOES WHAT</p><h2 id="sh-proof-title">Keys stay with you. Proofs enforce the spend.</h2></div><dl className="sh-responsibilities"><div><dt>Your browser</dt><dd>Generates your recovery secret and derives your spending, viewing and Ark wallet keys. It encrypts the local wallet backup with your passphrase and builds Groth16 proofs. This app does not upload your private keys.</dd></div><div><dt>The Shielded operator</dt><dd>Coordinates pool transactions and serves encrypted note data and public transaction history. It cannot substitute its signature for the required valid spend proof. You still depend on archive availability to restore and use your notes.</dd></div><div><dt>Arkade and the emulator</dt><dd>The configured public emulator checks the Groth16 verifier through its stock opcodes. The proof checks ownership, value conservation and note-spend rules. Arkade and emulator trust and availability still apply.</dd></div></dl><p className="sh-boundary">Deposits and withdrawals are visible money movements. This experiment does not hide every transaction or every piece of metadata.</p></section>
   <section id="recovery" className="sh-section sh-recovery" aria-labelledby="sh-recovery-title"><div className="sh-section-heading"><p className="sh-label">03 / BEFORE YOUR FIRST DEPOSIT</p><h2 id="sh-recovery-title">Save what only you can recover.</h2><p>Neither the Shielded operator nor this site can reset your secret.</p></div><div className="sh-recovery-content"><ol><li>Open the wallet and wait for pool setup to complete. Check and trust the installation fingerprint before creating a wallet.</li><li>Create a wallet with a strong passphrase. Save the recovery secret offline, or export the encrypted wallet backup and keep its passphrase.</li><li>Fund the Ark address shown in your customer wallet. Use only Mutinynet test BTC, then follow Deposit, Seal, Transfer and Withdraw.</li></ol><div className="sh-recovery-callout"><h3>If browser data gets wiped</h3><p>Restore with your recovery secret and the available operator archive, or import your encrypted backup with its passphrase. The operator's encrypted note data helps reconstruct notes; it does not replace your secret.</p><p>Losing both your secret and your usable backup means losing access to the notes. Archive withholding or loss can also block recovery.</p></div></div></section>
   <section className="sh-limits" aria-labelledby="sh-limits-title"><h2 id="sh-limits-title">What this test version can do</h2><p>BTC only, in one bounded shared pool with serialized state updates. It uses a development Groth16 circuit setup. Pool capacity is finite, and this version provides no independent note-holder pool exit during Arkade outages. It is not ready for mainnet funds.</p><a className="sh-button" href="/stock-wallet">Continue to the wallet <span aria-hidden="true">→</span></a></section>
  </main><footer className="sh-footer"><a href="/">Shielded / Arkade</a><span>Mutinynet · Experimental BTC pool</span><a href="#sh-title">Back to top ↑</a></footer>
 </div>;
}
