import React,{useEffect,useRef,useState} from 'react';
// @ts-ignore circomlibjs has no browser declarations.
import {buildPoseidon} from 'circomlibjs';
import {SingleKey,CSVMultisigTapscript,VtxoScript} from '@arkade-os/sdk';
import {hex} from '@scure/base';
import {bytesToHex} from '@noble/hashes/utils.js';
import {createStockBrowserClient} from '../../packages/protocol/src/browser-stock.ts';
import {deriveWalletKeyMaterial,parseMasterSecret} from '../../packages/protocol/src/wallet-keys.ts';
import {participantId,participantPublicKey,signParticipantRegistration,verifyParticipantRegistration,type RegistrationPayload} from '../../packages/protocol/src/registration.ts';
import {stockProofDescriptor,type StockSettlementProof} from '../../packages/protocol/src/stock-native.ts';
import type {ClientProtocolKernel,Owner,StockPreparedSettlement} from '../../packages/protocol/src/types.ts';
import {buildStockSpend,loadStockProfile,signCustomerFunding,stockVmRequest,type StockDraft} from '../../src/stock/sdk.ts';
import {openCustomerArkWallet,type CustomerVtxo} from '../../src/stock/ark-wallet.ts';
import {verifyStockArchive,stockReleaseFingerprint,type StockArchiveProfile,type VerifiedStockHead} from '../../src/stock/archive-client.ts';
import type {StockPublicArchive} from '../../src/stock/coordinator.ts';
import type {StockNetworkInfo} from '../../src/stock/network.ts';
import {decryptWallet,encryptWallet,type EncryptedWallet} from './wallet-backup.ts';

type Profile=StockArchiveProfile&{profile:string;participants:Record<string,RegistrationPayload>;ready:boolean;phase:17|18;head:{txid:string;vout:number;value:number;sourceTxHex:string};blockedReason:string;capacity:{remainingNoteRecords:number};proofSystem:string;setup:string;limitations:string[]};
type Archive=StockPublicArchive;
type StockPublicFunding={txid:string;vout:number;value:number;sourceTxHex:string;tapTreeHex:string;leafHex:string};
type Pending={prepared:StockPreparedSettlement;proof:StockSettlementProof;draft:StockDraft;externalFunding?:StockPublicFunding;externalProgram?:string};
interface WalletBackup {version:1;owner:Owner;network:'mutinynet';registrationProfile:string;trustedReleaseFingerprint:string;descriptorProfileId:string;masterSecret:string;lastVerifiedHead?:VerifiedStockHead;pending?:Pending}
const STORAGE='shielded-stock-wallet-v1';
const number=(value:string,label:string)=>{const n=Number(value);if(!Number.isSafeInteger(n)||n<1)throw new Error(`${label} must be a positive whole number of satoshis.`);return n;};

export default function StockWallet(){
 const [profile,setProfile]=useState<Profile>(),[wallet,setWallet]=useState<WalletBackup>(),[notes,setNotes]=useState<any[]>([]),[passphrase,setPassphrase]=useState(''),[recovery,setRecovery]=useState(''),[trustedReleaseFingerprint,setTrustedReleaseFingerprint]=useState(((import.meta as ImportMeta&{env?:Record<string,string|undefined>}).env?.VITE_STOCK_RELEASE_FINGERPRINT??'').toLowerCase()),[showRecovery,setShowRecovery]=useState(false),[amount,setAmount]=useState('1000'),[recipient,setRecipient]=useState(''),[destination,setDestination]=useState(''),[operation,setOperation]=useState<'deposit'|'transfer'|'withdraw'>('deposit'),[fundingCoins,setFundingCoins]=useState<CustomerVtxo[]>([]),[selectedFunding,setSelectedFunding]=useState(''),[arkAddress,setArkAddress]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const kernel=useRef<ClientProtocolKernel|undefined>(undefined),nativeSecret=useRef<string|undefined>(undefined),backupFile=useRef<EncryptedWallet|undefined>(undefined),verifiedArchive=useRef<Archive|undefined>(undefined),arkProgram=useRef<string|undefined>(undefined);
 const api=async<T=any>(path:string,body?:unknown):Promise<T>=>{const response=await fetch('/api'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await response.json();if(!response.ok)throw new Error(data.error??`Request failed (HTTP ${response.status})`);return data as T;};
 const save=async(value=wallet)=>{if(!value)return;const encrypted=await encryptWallet(value,passphrase);backupFile.current=encrypted;localStorage.setItem(STORAGE,JSON.stringify(encrypted));};
 const withBusy=async(action:()=>Promise<void>)=>{if(busy)return;setBusy(true);setMessage('');try{await action();}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}};
 const install=async(value:WalletBackup,current:Profile,archive:Archive)=>{
  if(value.network!=='mutinynet'||value.registrationProfile!==current.registration.profile||!value.trustedReleaseFingerprint)throw new Error('This wallet backup is missing its independently trusted Mutinynet release pin.');
  const verified=await verifyStockArchive(current,archive,value.trustedReleaseFingerprint,value.lastVerifiedHead);
  const keys=deriveWalletKeyMaterial(value.masterSecret,value.network),descriptorProfileId=stockProofDescriptor(current.verifierKey).profileId;
  if(value.descriptorProfileId!==descriptorProfileId)throw new Error('The registered Groth16 verifier changed. This backup cannot safely use the new profile.');
  const client=await createStockBrowserClient({owner:value.owner,keys:keys.keys,profile:current,checkpoint:verified.checkpoint});
  for(const entry of Object.values(archive.participants))if(!verifyParticipantRegistration(entry,'mutinynet',current.registration.profile))throw new Error('The public participant directory contains an invalid signature.');
  if(!archive.participants[value.owner]||archive.participants[value.owner].nativePublicKey!==participantPublicKey(keys.nativeSecret)||JSON.stringify(archive.participants[value.owner].recipient)!==JSON.stringify(client.publicDescriptor()))throw new Error('This recovery secret does not match a registered wallet.');
  client.setRecipients(verified.checkpoint.recipients);client.restorePublicCheckpoint(verified.checkpoint);value.lastVerifiedHead=verified.head;verifiedArchive.current=archive;kernel.current=client;nativeSecret.current=keys.nativeSecret;const ark=await openCustomerArkWallet(SingleKey.fromHex(keys.nativeSecret),current.network);arkProgram.current=ark.externalProgram;setArkAddress(ark.address);setFundingCoins(ark.coins);setSelectedFunding(ark.coins[0]?`${ark.coins[0].funding.txid}:${ark.coins[0].funding.vout}`:'');setDestination(ark.externalProgram);setWallet(value);setProfile(current);setNotes(client.recover(value.owner));await save(value);
  if(value.pending&&archive.history.some(entry=>JSON.stringify(entry.prepared)===JSON.stringify(value.pending!.prepared)&&JSON.stringify(entry.proof)===JSON.stringify(value.pending!.proof))){delete value.pending;await save(value);setMessage('A previously pending settlement was accepted and verified against its native transaction and proof.');}
 };
 const refresh=async()=>{const current=await api<Profile>('/profile');setProfile(current);const result=await api<{archive:Archive}>('/archive');return {current,archive:result.archive};};
 useEffect(()=>{void api<Profile>('/profile').then(setProfile).catch(error=>setMessage(error.message));},[]);
 const connect=async(value:WalletBackup)=>{
  let {current,archive}=await refresh();
  if(value.network!=='mutinynet'||!/^[0-9a-f]{64}$/.test(value.trustedReleaseFingerprint)||stockReleaseFingerprint(current.release)!==value.trustedReleaseFingerprint||value.registrationProfile!==current.registration.profile)throw new Error('This wallet backup does not match the independently trusted stock release.');
  await verifyStockArchive(current,archive,value.trustedReleaseFingerprint,value.lastVerifiedHead);
  const keys=deriveWalletKeyMaterial(value.masterSecret,value.network),owner=participantId(participantPublicKey(keys.nativeSecret));
  if(owner!==value.owner)throw new Error('The recovery secret does not match this wallet identity.');
  const client=await createStockBrowserClient({owner,keys:keys.keys,profile:current}),recipient=client.publicDescriptor(),known=archive.participants[owner];
  if(known){if(known.nativePublicKey!==participantPublicKey(keys.nativeSecret)||JSON.stringify(known.recipient)!==JSON.stringify(recipient))throw new Error('This owner is already registered to a different wallet descriptor.');}
  else{
   const registration=signParticipantRegistration({network:'mutinynet',profile:current.registration.profile,secretKey:keys.nativeSecret,recipient});
   await api('/participants/'+owner,registration);
   ({current,archive}=await refresh());
   await verifyStockArchive(current,archive,value.trustedReleaseFingerprint,value.lastVerifiedHead);
   const accepted=archive.participants[owner];
   if(!accepted||accepted.nativePublicKey!==participantPublicKey(keys.nativeSecret)||JSON.stringify(accepted.recipient)!==JSON.stringify(recipient))throw new Error('The operator did not accept this wallet registration. The encrypted backup is safe; retry unlock after checking the operator.');
  }
  await install(value,current,archive);
 };
 const create=()=>withBusy(async()=>{
  if(passphrase.length<12)throw new Error('Choose a wallet passphrase of at least 12 characters.');if(localStorage.getItem(STORAGE))throw new Error('A saved wallet exists. Unlock or export it first.');
  const current=await api<Profile>('/profile'),archive=(await api<{archive:Archive}>('/archive')).archive;if(!/^[0-9a-f]{64}$/.test(trustedReleaseFingerprint)||stockReleaseFingerprint(current.release)!==trustedReleaseFingerprint)throw new Error('Enter the release fingerprint from a trusted release channel; the value served by this operator cannot establish trust.');await verifyStockArchive(current,archive,trustedReleaseFingerprint);
  const master=crypto.getRandomValues(new Uint8Array(32)),masterSecret=bytesToHex(master),keys=deriveWalletKeyMaterial(master,'mutinynet'),owner=participantId(participantPublicKey(keys.nativeSecret));
  const descriptorProfileId=stockProofDescriptor(current.verifierKey).profileId;
  const value:WalletBackup={version:1,owner,network:'mutinynet',registrationProfile:current.registration.profile,trustedReleaseFingerprint,descriptorProfileId,masterSecret};
  await save(value);await connect(value);setRecovery(masterSecret);setShowRecovery(true);setMessage('Wallet created and signed registration saved. Copy the recovery secret now; it is never sent to the operator.');
 });
 const unlock=()=>withBusy(async()=>{if(passphrase.length<12)throw new Error('Enter the wallet passphrase.');const raw=JSON.parse(localStorage.getItem(STORAGE)??'null') as EncryptedWallet|null;if(!raw)throw new Error('No encrypted local wallet was found. Use the recovery secret to restore.');const value=await decryptWallet<WalletBackup>(raw,passphrase);await connect(value);setMessage('Wallet unlocked and notes restored from the signed operator archive.');});
 const recover=()=>withBusy(async()=>{if(passphrase.length<12)throw new Error('Choose a wallet passphrase of at least 12 characters.');const current=await api<Profile>('/profile');if(!/^[0-9a-f]{64}$/.test(trustedReleaseFingerprint))throw new Error('Enter the independently trusted release fingerprint before restoring.');const master=parseMasterSecret(recovery),keys=deriveWalletKeyMaterial(master,'mutinynet'),owner=participantId(participantPublicKey(keys.nativeSecret)),value:WalletBackup={version:1,owner,network:'mutinynet',registrationProfile:current.registration.profile,trustedReleaseFingerprint,descriptorProfileId:stockProofDescriptor(current.verifierKey).profileId,masterSecret:bytesToHex(master)};await save(value);await connect(value);setRecovery('');setShowRecovery(false);setMessage('Wallet keys and notes restored after verifying the trusted release, operator archive, proofs, native history, and current pool head.');});
 const reconcile=()=>withBusy(async()=>{await api('/reconcile',{});const {current,archive}=await refresh();if(wallet)await install(wallet,current,archive);if(wallet?.pending&&!archive.history.some(entry=>JSON.stringify(entry.prepared)===JSON.stringify(wallet.pending!.prepared)&&JSON.stringify(entry.proof)===JSON.stringify(wallet.pending!.proof)))setMessage('No matching accepted result is visible yet. The request was not resubmitted; keep this backup and reconcile again before creating another transaction.');else setMessage('Native transaction, proof history, and current unspent pool head were verified.');});
 const seal=()=>withBusy(async()=>{if(!kernel.current||!wallet)throw new Error('Unlock a wallet first.');const before=await refresh();await verifyStockArchive(before.current,before.archive,wallet.trustedReleaseFingerprint,wallet.lastVerifiedHead);await api('/seal',{});const result=await refresh();await install(wallet,result.current,result.archive);await save(wallet);setMessage('The public seal and its native history were verified. Your spending key was not sent.');});
 const refreshArkWallet=()=>withBusy(async()=>{if(!nativeSecret.current||!profile)throw new Error('Unlock the wallet first.');const ark=await openCustomerArkWallet(SingleKey.fromHex(nativeSecret.current),profile.network);arkProgram.current=ark.externalProgram;setArkAddress(ark.address);setDestination(ark.externalProgram);setFundingCoins(ark.coins);setSelectedFunding(ark.coins[0]?`${ark.coins[0].funding.txid}:${ark.coins[0].funding.vout}`:'');setMessage(`Arkade wallet refreshed: ${ark.coins.length} spendable BTC VTXOs.`);});
 const transact=(kind:'transfer'|'deposit'|'withdraw')=>withBusy(async()=>{
  if(!kernel.current||!wallet||!profile)throw new Error('Unlock a wallet first.');if(wallet.pending)throw new Error('A previous request is unresolved. Reconcile it before proceeding.');
  let current=await api<Profile>('/profile'),archive=(await api<{archive:Archive}>('/archive')).archive,verified=await verifyStockArchive(current,archive,wallet.trustedReleaseFingerprint,wallet.lastVerifiedHead);wallet.lastVerifiedHead=verified.head;kernel.current.setRecipients(verified.checkpoint.recipients);kernel.current.restorePublicCheckpoint(verified.checkpoint);
  if(!current.ready)throw new Error(current.blockedReason||'The stock pool is not ready.');if(archive.phase===17){await api('/prepare',{});current=await api<Profile>('/profile');archive=(await api<{archive:Archive}>('/archive')).archive;verified=await verifyStockArchive(current,archive,wallet.trustedReleaseFingerprint,wallet.lastVerifiedHead);wallet.lastVerifiedHead=verified.head;kernel.current.setRecipients(verified.checkpoint.recipients);kernel.current.restorePublicCheckpoint(verified.checkpoint);}
  const entered=Number(amount),selected=fundingCoins.find(coin=>`${coin.funding.txid}:${coin.funding.vout}`===selectedFunding),externalFunding=(kind==='deposit'||(kind==='withdraw'&&entered<current.network.dust))?selected?.funding:undefined;
  if((kind==='deposit'||(kind==='withdraw'&&number(amount,'Amount')<current.network.dust))&&!externalFunding)throw new Error('Select a spendable customer Arkade VTXO before continuing.');
  const qty=kind==='deposit'?externalFunding!.value:number(amount,'Amount'),prepared=kind==='deposit'?await kernel.current.prepareStockShield(wallet.owner,'BTC',qty):kind==='transfer'?await kernel.current.prepareStockTransfer(wallet.owner,recipient,'BTC',qty):await kernel.current.prepareStockWithdraw(wallet.owner,'BTC',qty,destination);
  const fundedWithdraw=kind==='withdraw'&&!!externalFunding,proofOperation=kind==='deposit'?'deposit':fundedWithdraw?'withdraw-funded':kind,request:any={profile:loadStockProfile(current.programs,current.verifierKey,current.release.descriptorProfileId,current.network,current.release.programsHash),operation:proofOperation,pool:{...archive.head,sourceTx:hex.decode(archive.head.sourceTxHex)},oldState:prepared.oldState,newState:prepared.newState,checkpoint:CSVMultisigTapscript.decode(hex.decode(current.checkpointTapscript)),hash:(values:bigint[])=>{throw new Error('Poseidon is initializing.');},weightLimit:current.network.weightLimit};
  if(externalFunding)request.externalFunding={...externalFunding,sourceTx:hex.decode(externalFunding.sourceTxHex),tapTree:hex.decode(externalFunding.tapTreeHex),tapLeafScript:VtxoScript.decode(hex.decode(externalFunding.tapTreeHex)).findLeaf(externalFunding.leafHex)};
  if(kind==='withdraw'){request.payoutBTC=prepared.boundary.withdrawal.BTC+(externalFunding?.value??0);request.externalProgram=destination;}
  const draft=await api<StockDraft>('/draft',{prepared,...(externalFunding?{externalFunding}:{}),...(kind==='withdraw'?{externalProgram:destination}:{})});
  if(!draft.nativeBinding)throw new Error('Operator did not return the native proof binding.');
  const proof=await kernel.current.proveStock(prepared,draft.nativeBinding),poseidon=await buildPoseidon();request.hash=(values:bigint[])=>BigInt(poseidon.F.toObject(poseidon(values)));
  const signedSpend=buildStockSpend(request,proof,draft),finalSpend=externalFunding?await signCustomerFunding(signedSpend,SingleKey.fromHex(nativeSecret.current!)):signedSpend;
  const pending:Pending={prepared,proof,draft,...(externalFunding?{externalFunding}:{}),...(kind==='withdraw'?{externalProgram:destination}:{})};wallet.pending=pending;await save(wallet);
  await api('/settlements',{prepared,proof,...(externalFunding?{externalFunding}:{}),signed:stockVmRequest(finalSpend)});
  const result=await refresh();await install(wallet,result.current,result.archive);await save(wallet);setMessage('The exact transaction was accepted and the signed public archive verified.');
 });
 const download=async()=>{if(!wallet)return;await save();const blob=new Blob([JSON.stringify(backupFile.current)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='shielded-stock-encrypted-backup.json';link.click();URL.revokeObjectURL(url);};
 const downloadArchive=()=>{if(!wallet||!verifiedArchive.current)throw new Error('Verify the current archive before exporting it.');const blob=new Blob([JSON.stringify({version:1,releaseFingerprint:wallet.trustedReleaseFingerprint,lastVerifiedHead:wallet.lastVerifiedHead,archive:verifiedArchive.current})],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='shielded-stock-verified-public-archive.json';link.click();URL.revokeObjectURL(url);};
 const importBackup=(file:File)=>withBusy(async()=>{const value=JSON.parse(await file.text()) as EncryptedWallet;localStorage.setItem(STORAGE,JSON.stringify(value));backupFile.current=value;setMessage('Encrypted backup imported. Enter its passphrase and unlock it.');});
 const short=(value:string)=>value?`${value.slice(0,10)}…${value.slice(-8)}`:'—';
 return <main className="stock-shell"><header className="stock-header"><div><span>ARKADE · MUTINYNET</span><h1>Shielded stock wallet</h1></div><a href="/">Legacy lab</a></header>
  <section className="stock-warning"><strong>Experimental stock-opcode profile</strong><span>BTC only · one shared pool · Groth16 proof in your browser · spending and viewing keys stay local.</span><span>Do not send funds unless the operator has confirmed the pinned verifier, network and weight profile.</span></section>
  {!wallet?<section className="stock-card"><h2>Create or recover a wallet</h2><label>Trusted release fingerprint<input inputMode="text" autoComplete="off" spellCheck={false} value={trustedReleaseFingerprint} onChange={e=>setTrustedReleaseFingerprint(e.target.value.trim().toLowerCase())}/></label><p className="stock-muted">Get this 64-character SHA-256 fingerprint from a release channel you trust, independently of this operator. The wallet blocks until the served verifier, proving artifacts, network and policy match it.</p><label>Wallet passphrase<input type="password" autoComplete="new-password" value={passphrase} onChange={e=>setPassphrase(e.target.value)}/></label><div className="stock-actions"><button disabled={busy||!/^[0-9a-f]{64}$/.test(trustedReleaseFingerprint)} onClick={()=>void create()}>Create wallet</button><button disabled={busy} onClick={()=>void unlock()}>Unlock saved wallet</button></div><label>Recovery secret<input value={recovery} onChange={e=>setRecovery(e.target.value)} autoComplete="off"/></label><button disabled={busy||!recovery||!/^[0-9a-f]{64}$/.test(trustedReleaseFingerprint)} onClick={()=>void recover()}>Restore from recovery secret</button><label className="stock-file">Import encrypted backup<input type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&void importBackup(e.target.files[0])}/></label></section>:<>
   <section className="stock-card"><div className="stock-row"><div><small>WALLET</small><code>{short(wallet.owner)}</code></div><div><small>POOL PHASE</small><strong>{profile?.phase===18?'Spend enabled':'Prepare required'}</strong></div><div><small>AVAILABLE NOTE RECORDS</small><strong>{profile?.capacity.remainingNoteRecords??'—'}</strong></div></div><h2>Your recovered notes</h2>{notes.length?<div className="stock-notes">{notes.filter(note=>!note.spent).map(note=><div key={note.index}><span>BTC note · #{note.index}</span><strong>{note.amount} sats</strong><code>{short(note.commitment)}</code></div>)}</div>:<p className="stock-muted">No spendable notes for this wallet yet.</p>}
    <div className="stock-actions"><button disabled={busy||!profile?.ready} onClick={()=>void seal()}>Seal current notes</button><button disabled={busy} onClick={()=>void reconcile()}>Reconcile pending result</button><button disabled={busy} onClick={()=>void download()}>Download encrypted wallet backup</button><button disabled={busy||!verifiedArchive.current} onClick={()=>void downloadArchive()}>Download verified public archive</button></div><p className="stock-muted">Keep both files. The wallet backup contains your encrypted key material; the public archive contains transaction metadata and encrypted note records and does not contain your spending key.</p>
   </section>
  <section className="stock-card"><h2>Client-authorized transaction</h2><label>Operation<select value={operation} onChange={e=>{const next=e.target.value as 'deposit'|'transfer'|'withdraw';setOperation(next);if(next==='transfer')setRecipient(Object.keys(profile?.participants??{}).find(owner=>owner!==wallet.owner)??'');}}><option value="deposit">Shield a customer Arkade VTXO</option><option value="transfer">Transfer to a registered wallet</option><option value="withdraw">Withdraw to my Arkade wallet</option></select></label>{operation==='deposit'&&<><div className="stock-address"><small>Your Arkade address</small><code>{arkAddress||'Loading…'}</code></div><button disabled={busy} onClick={()=>void refreshArkWallet()}>Refresh Arkade balance</button>{fundingCoins.length?<label>Spendable whole VTXO<select value={selectedFunding} onChange={e=>setSelectedFunding(e.target.value)}>{fundingCoins.map(coin=><option key={`${coin.funding.txid}:${coin.funding.vout}`} value={`${coin.funding.txid}:${coin.funding.vout}`}>{coin.amount} sats · {short(coin.funding.txid)}</option>)}</select></label>:<p className="stock-muted">Send BTC to this Arkade address, then refresh your wallet to select the received VTXO.</p>}<p className="stock-muted">This profile credits one exact whole Arkade VTXO; partial coin selection is disabled.</p></>}{operation==='transfer'&&<><label>Amount in satoshis<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Registered recipient<select value={recipient} onChange={e=>setRecipient(e.target.value)}>{Object.keys(profile?.participants??{}).filter(owner=>owner!==wallet.owner).map(owner=><option key={owner} value={owner}>{short(owner)}</option>)}</select></label></>}{operation==='withdraw'&&<><label>Claim amount in satoshis<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="stock-address"><small>Withdrawal destination</small><code>{destination||'Loading from your Arkade wallet…'}</code></div>{Number(amount||0)<(profile?.network.dust??330)&&<label>Customer Arkade VTXO to lift payout above dust<select value={selectedFunding} onChange={e=>setSelectedFunding(e.target.value)}>{fundingCoins.map(coin=><option key={`${coin.funding.txid}:${coin.funding.vout}`} value={`${coin.funding.txid}:${coin.funding.vout}`}>{coin.amount} sats · {short(coin.funding.txid)}</option>)}</select></label>}</>}
   <button disabled={busy||!!wallet.pending||!profile?.ready||(operation==='deposit'&&!fundingCoins.length)} onClick={()=>void transact(operation)}>Prove locally and submit once</button>{wallet.pending&&<p className="stock-blocked">A request is pending. Reconcile it; the wallet will not resubmit an unknown outcome.</p>}</section>
  </>}
  {showRecovery&&<section className="stock-card stock-recovery"><h2>Save this recovery secret</h2><p>It derives your private keys. The operator stores only your signed public descriptor and encrypted notes.</p><code>{recovery}</code><button onClick={()=>setShowRecovery(false)}>I saved it</button></section>}
  <section className="stock-card stock-meta"><span>Proof: {profile?.proofSystem??'loading'}</span><span>Setup: {profile?.setup??'loading'}</span><span>State: {profile?.blockedReason||'Ready checks come from the operator archive.'}</span>{profile?.limitations?.map(item=><small key={item}>{item}</small>)}</section>
  {message&&<p className="stock-message" role="status">{message}</p>}
 </main>;
}
